package api

import (
	"encoding/csv"
	"fmt"
	"net/http"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf/v2"
)

func severityOrder(sev string) int {
	switch strings.ToLower(sev) {
	case "critical":
		return 0
	case "high":
		return 1
	case "medium":
		return 2
	case "low":
		return 3
	default:
		return 4
	}
}

// handleExportFindingsCSV streams all findings for the tenant as CSV.
func (s *Server) handleExportFindingsCSV(w http.ResponseWriter, r *http.Request) {
	tenant := tenantFrom(r.Context())
	findings, err := s.db.ListFindings(r.Context(), tenant, "", "", 100000)
	if err != nil {
		s.writeError(w, http.StatusInternalServerError, err)
		return
	}

	w.Header().Set("Content-Type", "text/csv; charset=utf-8")
	w.Header().Set("Content-Disposition", `attachment; filename="castracloud-findings.csv"`)
	cw := csv.NewWriter(w)
	defer cw.Flush()

	_ = cw.Write([]string{
		"id", "severity", "status", "source", "rule_id", "title",
		"description", "remediation", "risk_score", "detected_at", "resolved_at",
	})
	for _, f := range findings {
		resolved := ""
		if f.ResolvedAt != nil {
			resolved = f.ResolvedAt.Format(time.RFC3339)
		}
		_ = cw.Write([]string{
			f.ID.String(),
			f.Severity,
			f.Status,
			f.Source,
			f.RuleID,
			f.Title,
			f.Description,
			f.Remediation,
			strconv.Itoa(f.RiskScore),
			f.DetectedAt.Format(time.RFC3339),
			resolved,
		})
	}
}

// handleExportReportPDF renders a security posture report as a PDF.
func (s *Server) handleExportReportPDF(w http.ResponseWriter, r *http.Request) {
	tenant := tenantFrom(r.Context())
	sum, err := s.db.FindingSummary(r.Context(), tenant)
	if err != nil {
		s.writeError(w, http.StatusInternalServerError, err)
		return
	}
	findings, err := s.db.ListFindings(r.Context(), tenant, "", "open", 100000)
	if err != nil {
		s.writeError(w, http.StatusInternalServerError, err)
		return
	}
	sort.Slice(findings, func(i, j int) bool {
		return severityOrder(findings[i].Severity) < severityOrder(findings[j].Severity)
	})

	score := 100 - (sum.Critical*10 + sum.High*5 + sum.Medium*2 + sum.Low*1)
	if score < 0 {
		score = 0
	}

	sevRGB := func(sev string) [3]int {
		switch strings.ToLower(sev) {
		case "critical":
			return [3]int{239, 68, 68}
		case "high":
			return [3]int{249, 115, 22}
		case "medium":
			return [3]int{234, 179, 8}
		case "low":
			return [3]int{34, 197, 94}
		default:
			return [3]int{156, 163, 175}
		}
	}
	scoreRGB := func(s int) [3]int {
		switch {
		case s >= 90:
			return [3]int{34, 197, 94}
		case s >= 75:
			return [3]int{132, 204, 22}
		case s >= 60:
			return [3]int{234, 179, 8}
		case s >= 40:
			return [3]int{249, 115, 22}
		default:
			return [3]int{239, 68, 68}
		}
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(12, 12, 12)
	pdf.SetAutoPageBreak(true, 18)
	pdf.AddPage()

	pdf.SetFooterFunc(func() {
		pdf.SetY(-15)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(150, 150, 150)
		pdf.CellFormat(0, 10, fmt.Sprintf("Generated by CastraCloud  |  Page %d", pdf.PageNo()), "", 0, "C", false, 0, "")
	})

	// Header band
	pdf.SetFillColor(17, 24, 39)
	pdf.Rect(0, 0, 210, 34, "F")
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 22)
	pdf.SetXY(12, 7)
	pdf.Cell(0, 10, "CastraCloud")
	pdf.SetFont("Helvetica", "", 12)
	pdf.SetXY(12, 19)
	pdf.Cell(0, 8, "Security Posture Report")

	pdf.SetTextColor(120, 120, 120)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetXY(12, 37)
	pdf.Cell(0, 6, "Generated: "+time.Now().Format("2006-01-02 15:04"))
	pdf.Ln(11)

	// Executive summary
	pdf.SetTextColor(17, 24, 39)
	pdf.SetFont("Helvetica", "B", 13)
	pdf.Cell(0, 8, "Executive Summary")
	pdf.Ln(8)
	pdf.SetFont("Helvetica", "", 10.5)
	pdf.SetTextColor(60, 60, 60)
	summaryText := fmt.Sprintf(
		"This tenant has %d total findings (%d open, %d resolved, %d suppressed). The current posture score is %d/100, with %d critical and %d high severity open issues requiring attention.",
		sum.Total, sum.Open, sum.Resolved, sum.Suppressed, score, sum.Critical, sum.High)
	if sum.Total == 0 {
		summaryText = "No findings have been recorded yet. Connect a cloud account and run a scan to establish your security posture."
	}
	pdf.MultiCell(0, 5.5, summaryText, "", "L", false)
	pdf.Ln(6)

	// Metric boxes
	boxW := 58.0
	boxH := 22.0
	gap := 6.0
	drawBox := func(x, y, w, h float64, value, label string, accent *[3]int) {
		pdf.SetFillColor(245, 246, 248)
		pdf.Rect(x, y, w, h, "F")
		if accent != nil {
			pdf.SetFillColor(accent[0], accent[1], accent[2])
			pdf.Rect(x, y, 3, h, "F")
		}
		pdf.SetFont("Helvetica", "B", 15)
		pdf.SetTextColor(17, 24, 39)
		pdf.SetXY(x+7, y+4)
		pdf.Cell(w-9, 8, value)
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(110, 110, 110)
		pdf.SetXY(x+7, y+15)
		pdf.Cell(w-9, 6, label)
	}

	scoreRGBVal := scoreRGB(score)
	highRGB := sevRGB("high")
	y0 := pdf.GetY()
	drawBox(12, y0, boxW, boxH, fmt.Sprintf("%d / 100", score), "Posture score", &scoreRGBVal)
	drawBox(12+boxW+gap, y0, boxW, boxH, strconv.Itoa(sum.Total), "Total findings", nil)
	drawBox(12+2*(boxW+gap), y0, boxW, boxH, strconv.Itoa(sum.Open), "Open", nil)
	y1 := y0 + boxH + gap
	drawBox(12, y1, boxW, boxH, strconv.Itoa(sum.Resolved), "Resolved", nil)
	drawBox(12+boxW+gap, y1, boxW, boxH, strconv.Itoa(sum.Suppressed), "Suppressed", nil)
	drawBox(12+2*(boxW+gap), y1, boxW, boxH, strconv.Itoa(sum.Critical+sum.High), "Critical + High", &highRGB)

	// Severity distribution
	pdf.SetXY(12, y1+boxH+gap+2)
	pdf.SetFont("Helvetica", "B", 13)
	pdf.SetTextColor(17, 24, 39)
	pdf.Cell(0, 8, "Severity Distribution")
	pdf.Ln(9)

	dist := []struct {
		label string
		count int
	}{
		{"Critical", sum.Critical},
		{"High", sum.High},
		{"Medium", sum.Medium},
		{"Low", sum.Low},
		{"Info", sum.Info},
	}
	maxCount := 1
	for _, d := range dist {
		if d.count > maxCount {
			maxCount = d.count
		}
	}
	for _, d := range dist {
		y := pdf.GetY()
		c := sevRGB(strings.ToLower(d.label))
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(60, 60, 60)
		pdf.SetXY(12, y+1)
		pdf.Cell(20, 5, d.label)
		pdf.SetXY(34, y+1)
		pdf.Cell(12, 5, strconv.Itoa(d.count))
		// track
		pdf.SetFillColor(232, 234, 237)
		pdf.Rect(48, y+2, 130, 4, "F")
		if d.count > 0 {
			pdf.SetFillColor(c[0], c[1], c[2])
			pdf.Rect(48, y+2, 130*float64(d.count)/float64(maxCount), 4, "F")
		}
		pdf.Ln(7)
	}
	pdf.Ln(4)

	// Open findings table
	drawTableHeader := func() {
		y := pdf.GetY()
		pdf.SetFillColor(17, 24, 39)
		pdf.Rect(12, y, 186, 8, "F")
		pdf.SetTextColor(255, 255, 255)
		pdf.SetFont("Helvetica", "B", 9)
		pdf.SetXY(14, y+2)
		pdf.Cell(16, 5, "SEVERITY")
		pdf.SetXY(32, y+2)
		pdf.Cell(30, 5, "RULE ID")
		pdf.SetXY(64, y+2)
		pdf.Cell(90, 5, "TITLE")
		pdf.SetXY(158, y+2)
		pdf.Cell(18, 5, "STATUS")
		pdf.SetXY(176, y+2)
		pdf.Cell(20, 5, "DETECTED")
		pdf.SetXY(12, y+8)
	}

	pdf.SetFont("Helvetica", "B", 13)
	pdf.SetTextColor(17, 24, 39)
	pdf.Cell(0, 8, fmt.Sprintf("Open Findings (%d)", len(findings)))
	pdf.Ln(8)

	if len(findings) == 0 {
		pdf.SetFont("Helvetica", "", 10.5)
		pdf.SetTextColor(60, 60, 60)
		pdf.Cell(0, 7, "No open findings.")
	} else {
		drawTableHeader()
		lineH := 5.0
		for i, f := range findings {
			titleLines := pdf.SplitText(f.Title, 90)
			rowH := float64(len(titleLines)) * lineH
			if rowH < 7 {
				rowH = 7
			}
			y := pdf.GetY()
			if y+rowH > 279 {
				pdf.AddPage()
				drawTableHeader()
				y = pdf.GetY()
			}
			if i%2 == 1 {
				pdf.SetFillColor(245, 246, 248)
				pdf.Rect(12, y, 186, rowH, "F")
			}
			c := sevRGB(f.Severity)
			pdf.SetFont("Helvetica", "B", 9)
			pdf.SetTextColor(c[0], c[1], c[2])
			pdf.SetXY(14, y+1)
			pdf.Cell(16, 5, strings.ToUpper(f.Severity))
			pdf.SetFont("Helvetica", "", 9)
			pdf.SetTextColor(60, 60, 60)
			pdf.SetXY(32, y+1)
			pdf.Cell(30, 5, f.RuleID)
			pdf.SetXY(64, y+1)
			pdf.MultiCell(90, lineH, f.Title, "", "L", false)
			pdf.SetXY(158, y+1)
			pdf.Cell(18, 5, f.Status)
			pdf.SetXY(176, y+1)
			pdf.Cell(20, 5, f.DetectedAt.Format("2006-01-02"))
			pdf.SetXY(12, y+rowH)
		}
	}

	w.Header().Set("Content-Type", "application/pdf")
	w.Header().Set("Content-Disposition", `attachment; filename="castracloud-report.pdf"`)
	if err := pdf.Output(w); err != nil {
		s.log.Error("pdf output failed", "error", err)
	}
}
